/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionMedecin;

import Login.Login;
import home.home;
import javax.swing.JOptionPane;

/**
 *
 * @author NAIMA BEKNCHICH
 */
public class gestionMedecin extends javax.swing.JFrame {

    /**
     * Creates new form gestionRdvs
     */
    public gestionMedecin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListeM = new javax.swing.JButton();
        AjoutM = new javax.swing.JButton();
        ModifierM = new javax.swing.JButton();
        UrgenceM = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListeM.setBackground(new java.awt.Color(204, 204, 204));
        ListeM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ListeM.setText("liste des médecins");
        ListeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeMActionPerformed(evt);
            }
        });
        getContentPane().add(ListeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 192, 247, 49));

        AjoutM.setBackground(new java.awt.Color(204, 204, 204));
        AjoutM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AjoutM.setText("Ajouter un médecin");
        AjoutM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutMActionPerformed(evt);
            }
        });
        getContentPane().add(AjoutM, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 120, 247, 49));

        ModifierM.setBackground(new java.awt.Color(204, 204, 204));
        ModifierM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ModifierM.setText("Modifier un médecin");
        ModifierM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierMActionPerformed(evt);
            }
        });
        getContentPane().add(ModifierM, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 326, 247, 49));

        UrgenceM.setBackground(new java.awt.Color(204, 204, 204));
        UrgenceM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UrgenceM.setText("Licencier un médecin");
        UrgenceM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrgenceMActionPerformed(evt);
            }
        });
        getContentPane().add(UrgenceM, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 259, 247, 49));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionMedecin/back.png"))); // NOI18N
        jButton5.setText("Retour");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 153, 50));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionMedecin/exit.png"))); // NOI18N
        jButton6.setText("Se déconnecter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 424, -1, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("Les médecins");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 33, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeMActionPerformed
         setVisible(false);
        ListeM obj=new ListeM();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ListeMActionPerformed

    private void AjoutMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutMActionPerformed
         setVisible(false);
        AjouterM ajt= new AjouterM();
        ajt.setVisible(true);
        dispose();
    }//GEN-LAST:event_AjoutMActionPerformed

    private void ModifierMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierMActionPerformed
        setVisible(false);
        ModifierM obj=new ModifierM();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModifierMActionPerformed

    private void UrgenceMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrgenceMActionPerformed
         setVisible(false);
        LicencierM obj=new LicencierM();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_UrgenceMActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
        home obj=new home();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "voulez-vous vraiment fermer l'application!","select",JOptionPane.YES_NO_CANCEL_OPTION);
        if (a==0)
        {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionMedecin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutM;
    private javax.swing.JButton ListeM;
    private javax.swing.JButton ModifierM;
    private javax.swing.JButton UrgenceM;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
